name: Terraform-Apply-Infra-Release

on:
  push:
    branches:
      - master


jobs:
  terraform_apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        run: terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

