name: Terraform-Apply-Infra-CD

on:
  workflow_dispatch:

jobs:
  manual_trigger:
    name: "Manual Trigger"
    runs-on: ubuntu-latest
    steps:
      - name: Manual Trigger
        run: echo "Manually triggered CD workflow"

  terraform_apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: manual_trigger
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform plan from CI artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        run: terraform apply tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
