name: Terraform-Apply-Infra-CD

on:
  workflow_run:
    workflows: ["Terraform-Apply-Infra-Release"]
    types:
      - completed

jobs:
  terraform_apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: Terraform-Apply-Infra-Release.terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        run: terraform apply tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
