name: "Terraform-Apply-Infra-Release"
on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout aws
        uses: actions/checkout@v2

      - name: Add modules as submodule
        run: git submodule add https://github.com/sanghaviar/modules

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Publish Terraform Plan Artifact
        if: steps.plan.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: tfplan
      - name: Store workflow run ID and artifact name
        id: store_workflow_info
        run: |
            echo "::set-output name=workflow_run_id::${{ github.run_id }}"
            echo "::set-output name=artifact_name::terraform-plan"  

  terraform1:
    name: "Terraform1"
    runs-on: ubuntu-latest
    needs: Terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Plan
        run: terraform plan -out=new_tfplan
        working-directory: tfplan

      - name: Terraform Apply
        run: terraform apply --auto-approve new_tfplan
        working-directory: tfplan
